# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-13 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('response', models.TextField()),
                ('dimension', models.CharField(max_length=100)),
            ],
        ),
    ]
