# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-13 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cache',
            old_name='response',
            new_name='content',
        ),
        migrations.AddField(
            model_name='cache',
            name='status',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
